### ISSUE TITLE
Sprint 10

### ISSUE THREAD

**Issue by mrprovoker** [AleksandrHexlet/validation.github.io#1]
Добрый день

Очень хорошая работа, полностью выполена проверка на имя

**Надо исправить:**
- Не проходит проверку валидный email: `mysite@you.me.net`, `my.ownsite@ourearth.org`
- Не проходит валидацию телефон из подсказки: `+7 (900) 000-00-00`
- Не проходит валидацию валидный IP: `http://127.0.0.1`
- Проходит валидацию такой IP-адрес: `http://www.255.255.255.255`
- Максимальный допустимый порт из определения - 65535. Сейчас проходит проверку такой адрес: `http://255.255.255.255:65536`
- Проходит валидацию `http://mysite.23`, tld из цифр состоять не может.

Можно лучше:
- README получилось очень маленьким и коротким. Рекомендуется добавить описание проекта, ссылку на проект на github.io, а также добавить инструкцию как развернуть проект локально.
- Обычно файл `README.md` принято называть заглавными буквами.

**Comment by mrprovoker** [comment]
Спасибо за правки. Появилось еще проблема:

**Надо исправить:**
- Не проходит url с портом: https://mysite.ru:8080

После исправлений замечаний необходимо убедиться, что все пункты задания выполнены, все проверки проходят по ссылке проекта на github.io.

Работу смогу принять только после устранения всех замечаний из пункта **Надо исправить**.

**Comment by mrprovoker** [comment]
Спасибо за правки. 

После правки появилось еще проблема.

Надо исправить:
- Проходит url с портом: `https://mysite.ru:8` или `https://mysite.ru:`. 

> Согласно заданию: порт — тоже необязательная группа. Порт начинается с двоеточия, за которым идут **от 2 до 5 цифр**


После исправлений замечаний необходимо убедиться, что все пункты задания выполнены, все проверки проходят по ссылке проекта на github.io.

Работу смогу принять только после устранения всех замечаний из пункта Надо исправить.

**Comment by mrprovoker** [comment]
Спасибо за правки. Теперь работа отличная.

Все пункты задания выполнены в полном объеме. Задание принято 👍

Желаю успехов в дальнейшем обучении!

**Comment by AleksandrHexlet** [comment]
Сергей , добрый день.
Спасибо вам большое за добрые слова и конструктивную обратную связь. С вами очень приятно работать.
Хорошего вам дня и отличной недели.👍👍👍


Четверг, 19 марта 2020, 10:13 +03:00 от Sergei Grobov <notifications@github.com>:
>Спасибо за правки. Теперь работа отличная.
>Все пункты задания выполнены в полном объеме. Задание принято 👍
>Желаю успехов в дальнейшем обучении!
>—
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .

-- 
А.В.К.
